defaults:
  - default
  - _self_

hydra:
  job:
    name: pusht

eval_episodes: 50
eval_freq: 7500
save_freq: 75000
fps: 10

env:
  name: pusht
  task: pusht
  image_size: 96
  fps: ${fps}
  action_repeat: 1
  episode_length: 300

policy:
  state_dim: 2
  action_dim: 2