# @package _global_

hydra:
  job:
    name: pusht

eval_episodes: 50
eval_freq: 7500
save_freq: 75000
train_steps: 50000  # TODO: same as simxarm, need to adjust

fps: 10

env:
  name: pusht
  task: pusht
  from_pixels: True
  pixels_only: False
  image_size: 96
  action_repeat: 1
  episode_length: 300

policy:
  state_dim: 2
  action_dim: 2